### ISSUE TITLE
Conflict not resolved

### ISSUE THREAD

**Issue by rjwb1** [RaymondKirk/rasberry_perception#15]
Is this intentional? 

https://github.com/RaymondKirk/rasberry_perception/blob/5813fa5b067a6be9ab46f3ede364fe8f3298b72e/launch/detector.launch#L12-L26

**Comment by RaymondKirk** [comment]
It is not, can’t fix atm! A pr would be appreciated if you’re available?

On 2 May 2021, at 14:00, Robert Belshaw ***@***.***> wrote:

﻿

Is this intentional?

https://github.com/RaymondKirk/rasberry_perception/blob/5813fa5b067a6be9ab46f3ede364fe8f3298b72e/launch/detector.launch#L12-L26

**Comment by rjwb1** [comment]
Fixed in #16
